# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: 'install npm'
          command: |
            sudo apt install npm
            npm install
      - run:
          name: 'build'
          command: |
            pwd
            echo "-----------------This is working directory"
            npm run build
            ls

workflows:
  say-hello-workflow:
    jobs:
      - build
